-- ============================================================================
-- Nodeframe — generalized backend schema (Supabase / Postgres)
-- ----------------------------------------------------------------------------
-- Replaces the old project's one-table-per-sensor design (dht11_readings,
-- mq6_readings, ultrasonic_readings, ...) with a plugin-driven schema: any
-- sensor module — installed or not-yet-built — is described by one row in
-- `plugins`, not a new table. Adding a new sensor type is a manifest, not a
-- firmware rebuild.
--
-- This version matches the actual hackathon build: 4 sensors are physically
-- wired to the ESP32 and have rows in `modules`; 4 more plugin manifests
-- exist (in `plugins`, with installed = false) proving the format works for
-- sensors the team hasn't had the power budget to wire up yet. There is no
-- "community marketplace" table here on purpose — every plugin, installed or
-- not, is authored by the team; we don't fabricate a user base.
-- ============================================================================

-- A plugin is a sensor driver + manifest. `installed` reflects whether it's
-- physically wired to a core right now; `target_slot` is where it would go
-- if/when it is. metric_key/unit are nullable — an event-only plugin (like
-- access-control) has no continuous reading to plot.
create table public.plugins (
  slug            text primary key,             -- e.g. 'sound-level'
  name            text not null,                -- e.g. 'Sound Sensor'
  sensor_chip     text,                          -- e.g. 'HC-SR04 (Ultrasonic)'
  category        text not null default 'Sensing',
  metric_key      text,                          -- primary metric, e.g. 'temperature'; null if event-only
  unit            text,                          -- e.g. '°C'; null if event-only
  warn_above      numeric,
  crit_above      numeric,
  warn_below      numeric,
  crit_below      numeric,
  author          text not null default 'nodeframe-core',
  installed       boolean not null default false,
  target_slot     text,                          -- where it would seat once installed
  description     text,
  created_at      timestamptz not null default now()
);

-- A module is one physical sensor plugged into one slot on one core, running
-- a given plugin. Only plugins with installed = true have a row here.
create table public.modules (
  id              text primary key,              -- e.g. 'mod-sound-01', assigned at pairing time
  plugin_slug     text not null references public.plugins(slug),
  label           text not null,
  slot            text not null,                 -- physical slot id, e.g. 'A1'
  core_id         text not null default 'core-01',
  status          text not null default 'good'
                    check (status in ('good','warning','critical','offline')),
  connected_at    timestamptz not null default now(),
  last_seen_at    timestamptz not null default now()
);

-- Every reading from every installed module lands here, tagged with the
-- metric key and unit from the owning plugin.
create table public.readings (
  id              bigint generated by default as identity primary key,
  module_id       text not null references public.modules(id) on delete cascade,
  metric_key      text not null,
  value           double precision not null,
  unit            text not null,
  recorded_at     timestamptz not null default now()
);
create index readings_module_time_idx on public.readings (module_id, recorded_at desc);

-- Discrete events: threshold crossings, trend flags, connect/disconnect,
-- firmware updates. (No RFID-scan rows in this build's seed data — that
-- plugin isn't installed — but the table stays generic enough to carry them
-- once it is: event_type = 'access', meta = {"card_uid": ..., "authorized": ...}.)
create table public.events (
  id              bigint generated by default as identity primary key,
  module_id       text references public.modules(id) on delete set null,
  event_type      text not null,                 -- 'threshold' | 'trend' | 'connect' | 'disconnect' | 'firmware' | 'access'
  severity        text not null default 'info'
                    check (severity in ('info','warning','critical')),
  message         text not null,
  meta            jsonb not null default '{}',
  created_at      timestamptz not null default now()
);
create index events_created_idx on public.events (created_at desc);

-- Disable Row Level Security so the core hub can insert with the anon key
-- (tighten this before shipping past a hackathon demo).
alter table public.plugins  disable row level security;
alter table public.modules  disable row level security;
alter table public.readings disable row level security;
alter table public.events   disable row level security;
